package uk.org.blackwood.uhresttest;

import android.content.ContentResolver;
import android.database.sqlite.SQLiteDatabase;
import android.util.Log;

public class HousingTenantsHouseholdTable {
	// Table defaults
	public static final String COLUMN_ID = "_id";
	public static final String COLUMN_ID_DEFAULTS = " INTEGER PRIMARY KEY AUTOINCREMENT ";
	public static final String COLUMN_TEXT_DEFAULTS = " TEXT NOT NULL ";
	public static final String COLUMN_INT_DEFAULTS = " INTEGER ";
	public static final String COLUMN_SEPARATOR = ", ";
	public static final String TABLE_HOUSING_TENANTS_HOUSEHOLD = "housing_tenants_household";
	public static final String API_PATH = "/housing/tenants/household/";
	public static final String CONTENT_PATH = "/housing/tenants/household";

	// Columns
	public static final String COLUMN_HOUSING_TENANTS_HOUSEHOLD_HOUSE_REF = "house_ref";
	public static final String COLUMN_HOUSING_TENANTS_HOUSEHOLD_PERSON_NO = "person_no";
	public static final String COLUMN_HOUSING_TENANTS_HOUSEHOLD_ETHNIC_ORIGIN = "ethnic_origin";
	public static final String COLUMN_HOUSING_TENANTS_HOUSEHOLD_GENDER = "gender";
	public static final String COLUMN_HOUSING_TENANTS_HOUSEHOLD_TITLE = "title";
	public static final String COLUMN_HOUSING_TENANTS_HOUSEHOLD_FORENAME = "forename";
	public static final String COLUMN_HOUSING_TENANTS_HOUSEHOLD_SURNAME = "surname";
	public static final String COLUMN_HOUSING_TENANTS_HOUSEHOLD_RELATIONSHIP = "relationship";
	public static final String COLUMN_HOUSING_TENANTS_HOUSEHOLD_DOB = "dob";
	public static final String COLUMN_HOUSING_TENANTS_HOUSEHOLD_NI_NO = "ni_no";
	
	// Projections
	public static final String [] PROJECTION_HOUSING_TENANTS_HOUSEHOLD_SUMMARY = {
		COLUMN_ID, COLUMN_HOUSING_TENANTS_HOUSEHOLD_HOUSE_REF, COLUMN_HOUSING_TENANTS_HOUSEHOLD_TITLE,
		COLUMN_HOUSING_TENANTS_HOUSEHOLD_FORENAME, COLUMN_HOUSING_TENANTS_HOUSEHOLD_SURNAME,
		COLUMN_HOUSING_TENANTS_HOUSEHOLD_RELATIONSHIP, COLUMN_HOUSING_TENANTS_HOUSEHOLD_DOB, COLUMN_HOUSING_TENANTS_HOUSEHOLD_NI_NO
	};
	public static final String [] PROJECTION_HOUSING_TENANTS_HOUSEHOLD_ALL = {
		COLUMN_ID, COLUMN_HOUSING_TENANTS_HOUSEHOLD_HOUSE_REF, COLUMN_HOUSING_TENANTS_HOUSEHOLD_PERSON_NO,
		COLUMN_HOUSING_TENANTS_HOUSEHOLD_ETHNIC_ORIGIN, COLUMN_HOUSING_TENANTS_HOUSEHOLD_GENDER, COLUMN_HOUSING_TENANTS_HOUSEHOLD_TITLE,
		COLUMN_HOUSING_TENANTS_HOUSEHOLD_FORENAME, COLUMN_HOUSING_TENANTS_HOUSEHOLD_SURNAME, COLUMN_HOUSING_TENANTS_HOUSEHOLD_RELATIONSHIP,
		COLUMN_HOUSING_TENANTS_HOUSEHOLD_DOB, COLUMN_HOUSING_TENANTS_HOUSEHOLD_NI_NO
	};
	
	// CREATE TABLE SQL
	public static final String CREATE_HOUSING_TENANTS_HOUSEHOLD = 
		"CREATE TABLE " + TABLE_HOUSING_TENANTS_HOUSEHOLD + "("
		+ COLUMN_ID + COLUMN_ID_DEFAULTS + COLUMN_SEPARATOR
		+ COLUMN_HOUSING_TENANTS_HOUSEHOLD_HOUSE_REF + COLUMN_TEXT_DEFAULTS + COLUMN_SEPARATOR
		+ COLUMN_HOUSING_TENANTS_HOUSEHOLD_PERSON_NO + COLUMN_INT_DEFAULTS + COLUMN_SEPARATOR
		+ COLUMN_HOUSING_TENANTS_HOUSEHOLD_ETHNIC_ORIGIN + COLUMN_TEXT_DEFAULTS + COLUMN_SEPARATOR
		+ COLUMN_HOUSING_TENANTS_HOUSEHOLD_GENDER + COLUMN_TEXT_DEFAULTS + COLUMN_SEPARATOR
		+ COLUMN_HOUSING_TENANTS_HOUSEHOLD_TITLE + COLUMN_TEXT_DEFAULTS + COLUMN_SEPARATOR
		+ COLUMN_HOUSING_TENANTS_HOUSEHOLD_FORENAME + COLUMN_TEXT_DEFAULTS + COLUMN_SEPARATOR
		+ COLUMN_HOUSING_TENANTS_HOUSEHOLD_SURNAME + COLUMN_TEXT_DEFAULTS + COLUMN_SEPARATOR
		+ COLUMN_HOUSING_TENANTS_HOUSEHOLD_RELATIONSHIP + COLUMN_TEXT_DEFAULTS + COLUMN_SEPARATOR
		+ COLUMN_HOUSING_TENANTS_HOUSEHOLD_DOB + COLUMN_TEXT_DEFAULTS + COLUMN_SEPARATOR
		+ COLUMN_HOUSING_TENANTS_HOUSEHOLD_NI_NO + COLUMN_TEXT_DEFAULTS + ");";
	
	public static void onCreate(SQLiteDatabase db) {
		Log.d("HousingTenantsCommsTable", "Executing " + CREATE_HOUSING_TENANTS_HOUSEHOLD);
		db.execSQL(CREATE_HOUSING_TENANTS_HOUSEHOLD);
	}
	
	public static void onUpgrade(SQLiteDatabase db, int oldVer, int newVer) {
		// Upgrade - clear down existing data, recreate and pull down
		Log.w(UHRESTTestHelper.class.getName(), "Upgrading database from version "+ oldVer + " to"
			+ newVer + " which will destroy all old data");
		db.execSQL("DROP TABLE IF EXISTS " + TABLE_HOUSING_TENANTS_HOUSEHOLD);
		onCreate(db);
		ContentResolver.requestSync(HomescreenActivity.exAcct, HomescreenActivity.AUTHORITY, null);
	}
}
