package uk.org.blackwood.uhresttest;

import android.content.ContentResolver;
import android.database.sqlite.SQLiteDatabase;
import android.util.Log;

public class HousingTenantsTable {
	// Table defaults
	public static final String COLUMN_ID = "_id";
	public static final String COLUMN_ID_DEFAULTS = " INTEGER PRIMARY KEY AUTOINCREMENT ";
	public static final String COLUMN_TEXT_DEFAULTS = " TEXT NOT NULL ";
	public static final String COLUMN_INT_DEFAULTS = " INTEGER ";
	public static final String COLUMN_SEPARATOR = ", ";
	public static final String TABLE_HOUSING_TENANTS = "housing_tenants";
	public static final String API_PATH = "/housing/tenants/officer/";

	// Columns
	public static final String COLUMN_HOUSING_TENANTS_TAG_REF = "tag_ref";
	public static final String COLUMN_HOUSING_TENANTS_SURNAME = "surname";
	public static final String COLUMN_HOUSING_TENANTS_FORENAME = "forename";
	public static final String COLUMN_HOUSING_TENANTS_TITLE = "title";
	public static final String COLUMN_HOUSING_TENANTS_POST_DESIG = "post_desig";
	public static final String COLUMN_HOUSING_TENANTS_ADDRESS = "address";
	public static final String COLUMN_HOUSING_TENANTS_SCHEME_REF = "scheme_ref";
	public static final String COLUMN_HOUSING_TENANTS_PERSON_NO = "person_no";
	public static final String COLUMN_HOUSING_TENANTS_ETHNIC_ORIGIN = "ethnic_origin";
	public static final String COLUMN_HOUSING_TENANTS_HOUSE_REF = "house_ref";
	public static final String COLUMN_HOUSING_TENANTS_AREA_OFFICE_DESC = "area_office_desc";
	public static final String COLUMN_HOUSING_TENANTS_SCHEME_NAME = "SchemeName";
	public static final String COLUMN_HOUSING_TENANTS_CHECK_DETAILS = "check_details";
	public static final String COLUMN_HOUSING_TENANTS_DOB = "dob";
	public static final String COLUMN_HOUSING_TENANTS_NI_NO = "ni_no";
	public static final String COLUMN_HOUSING_TENANTS_CON_KEY = "con_key";
	public static final String COLUMN_HOUSING_TENANTS_PROP_REF = "prop_ref";
	public static final String COLUMN_HOUSING_TENANTS_POST_CODE = "post_code";

	// Projections
	public static final String [] PROJECTION_HOUSING_TENANTS_SUMMARY = {COLUMN_ID, COLUMN_HOUSING_TENANTS_TITLE,
		COLUMN_HOUSING_TENANTS_FORENAME, COLUMN_HOUSING_TENANTS_SURNAME, COLUMN_HOUSING_TENANTS_POST_DESIG, COLUMN_HOUSING_TENANTS_ADDRESS,
		COLUMN_HOUSING_TENANTS_CHECK_DETAILS, COLUMN_HOUSING_TENANTS_POST_CODE};
	public static final String [] PROJECTION_HOUSING_TENANTS_ALL = {COLUMN_ID, COLUMN_HOUSING_TENANTS_TAG_REF,
		COLUMN_HOUSING_TENANTS_SURNAME, COLUMN_HOUSING_TENANTS_FORENAME, COLUMN_HOUSING_TENANTS_TITLE,
		COLUMN_HOUSING_TENANTS_POST_DESIG, COLUMN_HOUSING_TENANTS_ADDRESS, COLUMN_HOUSING_TENANTS_SCHEME_REF,
		COLUMN_HOUSING_TENANTS_PERSON_NO, COLUMN_HOUSING_TENANTS_ETHNIC_ORIGIN, COLUMN_HOUSING_TENANTS_HOUSE_REF,
		COLUMN_HOUSING_TENANTS_AREA_OFFICE_DESC, COLUMN_HOUSING_TENANTS_SCHEME_NAME, COLUMN_HOUSING_TENANTS_CHECK_DETAILS,
		COLUMN_HOUSING_TENANTS_DOB, COLUMN_HOUSING_TENANTS_NI_NO, COLUMN_HOUSING_TENANTS_CON_KEY,
		COLUMN_HOUSING_TENANTS_PROP_REF};

	// SQL
	public static final String CREATE_TENANTS =
		"CREATE TABLE " + TABLE_HOUSING_TENANTS + " ("
		+ COLUMN_ID + COLUMN_ID_DEFAULTS + COLUMN_SEPARATOR
		+ COLUMN_HOUSING_TENANTS_TAG_REF + COLUMN_TEXT_DEFAULTS + COLUMN_SEPARATOR
		+ COLUMN_HOUSING_TENANTS_SURNAME + COLUMN_TEXT_DEFAULTS + COLUMN_SEPARATOR
		+ COLUMN_HOUSING_TENANTS_FORENAME + COLUMN_TEXT_DEFAULTS + COLUMN_SEPARATOR
		+ COLUMN_HOUSING_TENANTS_TITLE + COLUMN_TEXT_DEFAULTS + COLUMN_SEPARATOR
		+ COLUMN_HOUSING_TENANTS_POST_DESIG + COLUMN_TEXT_DEFAULTS + COLUMN_SEPARATOR
		+ COLUMN_HOUSING_TENANTS_ADDRESS + COLUMN_TEXT_DEFAULTS + COLUMN_SEPARATOR
		+ COLUMN_HOUSING_TENANTS_SCHEME_REF + COLUMN_TEXT_DEFAULTS + COLUMN_SEPARATOR
		+ COLUMN_HOUSING_TENANTS_PERSON_NO + COLUMN_INT_DEFAULTS + COLUMN_SEPARATOR
		+ COLUMN_HOUSING_TENANTS_ETHNIC_ORIGIN + COLUMN_TEXT_DEFAULTS + COLUMN_SEPARATOR
		+ COLUMN_HOUSING_TENANTS_HOUSE_REF + COLUMN_TEXT_DEFAULTS + COLUMN_SEPARATOR
		+ COLUMN_HOUSING_TENANTS_AREA_OFFICE_DESC + COLUMN_TEXT_DEFAULTS + COLUMN_SEPARATOR
		+ COLUMN_HOUSING_TENANTS_SCHEME_NAME + COLUMN_TEXT_DEFAULTS + COLUMN_SEPARATOR
		+ COLUMN_HOUSING_TENANTS_CHECK_DETAILS + COLUMN_TEXT_DEFAULTS + COLUMN_SEPARATOR
		+ COLUMN_HOUSING_TENANTS_DOB + COLUMN_TEXT_DEFAULTS + COLUMN_SEPARATOR
		+ COLUMN_HOUSING_TENANTS_NI_NO + COLUMN_TEXT_DEFAULTS + COLUMN_SEPARATOR
		+ COLUMN_HOUSING_TENANTS_CON_KEY + COLUMN_INT_DEFAULTS + COLUMN_SEPARATOR
		+ COLUMN_HOUSING_TENANTS_PROP_REF + COLUMN_TEXT_DEFAULTS + COLUMN_SEPARATOR
		+ COLUMN_HOUSING_TENANTS_POST_CODE + COLUMN_TEXT_DEFAULTS + ");";
	
	public static void onCreate(SQLiteDatabase db) {
		db.execSQL(CREATE_TENANTS);
	}
	
	public static void onUpgrade(SQLiteDatabase db, int oldVer, int newVer) {
		// Upgrade - clear down existing data, recreate and pull down
		Log.w(UHRESTTestHelper.class.getName(), "Upgrading database from version "+ oldVer + " to"
			+ newVer + " which will destroy all old data");
		db.execSQL("DROP TABLE IF EXISTS " + TABLE_HOUSING_TENANTS);
		onCreate(db);
		ContentResolver.requestSync(HomescreenActivity.exAcct, HomescreenActivity.AUTHORITY, null);
	}
}
